# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Blog
tagline:          'A repository of ideas'
description:      'There will be a description soon.'
url:              http://blog.ranveeraggarwal.com
baseurl:          /

author:
  name:           'Ranveer Aggarwal'
  url:            https://twitter.com/ranveeraggarwal

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ranveeraggarwal/ranveeraggarwal.github.io
