# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Ranveer Aggarwal | Blog
tagline:          'A repository of ideas'
description:      'A Repository of Ideas and Thoughts.'
url:              http://blog.ranveeraggarwal.com
baseurl:          /

author:
  name:           'Ranveer Aggarwal'
  url:            https://twitter.com/ranveeraggarwal
  email:		  ranveeraggarwal@gmail.com

paginate:         5

# Custom vars
version:          1.0.1

github:
  repo:           https://github.com/ranveeraggarwal/ranveeraggarwal.github.io
