# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink: /:categories/:title

# Setup
title:            Ranveer Aggarwal
tagline:          'My Personal Webspace'
description:      'A Repository of Ideas and Thoughts.'
url:              http://www.ranveeraggarwal.com
baseurl:          /

author:
  name:           'Ranveer Aggarwal'
  url:            https://twitter.com/ranveeraggarwal
  email:		  ranveeraggarwal@gmail.com

paginate:         6
paginate_path: 	  "blog/page:num/"

#gems
#gems:
#   - jekyll-sitemap

# Custom vars
version:          1.1.0

github:
  repo:           https://github.com/ranveeraggarwal/ranveeraggarwal.github.io
