---
layout: blog
title: "Getting Started With Jekyll on Github Pages"
category: blog
---

What is Jekyll?

Jekyll is a blog-aware, static site generator in Ruby. It is commonly used by Github users to write small blogs, or display their hacks. This blog by the way is also generated by Jekyll.

Firstly, I'd like to clarify what this little post is about. It won't *teach* you Jekyll, it'll just help you set up your *username.github.io* on Jekyll. If you want to learn more about it, check out the repo on Github or visit the homepage.

Now, many people are confused as to where to get started. The first thing you get when you Google it out is the quickstart guide with instructions like:

	~ $ gem install jekyll
	~ $ jekyll new my-awesome-site

and so on. All this isn't required on Github. It's already up and running there.

So here are the brief steps you need to follow to create your blog/hack page on Github pages:

* First, create a *repo* with the name *username.github.io*, where *username* is your username.
* Next, create a file with the name **_config.yml**. This is a file that contains all the configuration variables for your site in the [YAML](http://en.wikipedia.org/wiki/YAML) format. You can use any text editor for this (I prefer Sublime Text 3). Now put the following content in your file:

	markdown: rdiscount
	permalink: /:title
	pygments: true
	auto: true
	rdiscount:
	  extensions: [smart]

and save it and push it in the main repo.
